local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, KEYMAP_OPTS)
vim.keymap.set("n", "<leader>fF", ":Telescope find_files hidden=true no_ignore=true<CR>", KEYMAP_OPTS)
vim.keymap.set("n", "<leader>fw", builtin.live_grep, KEYMAP_OPTS)
vim.keymap.set("n", "<leader>fb", builtin.buffers, KEYMAP_OPTS)
vim.keymap.set("n", "<leader>fh", builtin.help_tags, KEYMAP_OPTS)
